language: julia

os:
  - linux

julia:
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg;
                        Pkg.instantiate();
                        Pkg.develop(PackageSpec(path=pwd()));'
        - julia --project=docs/ docs/make.jl
      after_success: skip
